openapi: 3.0.3
info:
  title: Planning Poker
  description: Planning Poker
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/'
paths:
  /games/{id}/join:
    post:
      parameters:
        - name: id
          in: path
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
      responses:
        202:
          description: "Accepted"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    required: true
  
